### ISSUE TITLE
Wondering if AGPL is appropriate

### ISSUE THREAD

**Issue by prolixalias** [voxpupuli/voxpupuli-puppet-lint-plugins#56]
Hello! The license, "GNU Affero General Public License v3.0" causes some orgs to quarantine in nexus due to perceived ambiguity on whether they're subject to making puppet code resulting/benefiting from puppet-lint-plugins - public. 

Current engagement is one of them but it's not the first. The reason this one is a problem is they're unwavering on a waiver. We just can't use it.

Was AGPL chosen over other, similar licenses that don't have the requirement for sharing source code out of necessity when using puppet-lint-plugins?

Any clarity I can relay back to the nexus team here would be quite helpful.

**Comment by kenyon** [comment]
What is the logic behind the idea that puppet code processed by these lint plugins would need to be released publicly? I don't see how one could come to that conclusion due to the AGPL. https://www.gnu.org/licenses/why-affero-gpl.html

**Comment by prolixalias** [comment]
@kenyon  - I don't have an issue with that license. However, it's a somewhat common concern with legal teams at behemoth companies like the one I'm at temporarily. They've interpreted that "use" in workflow constitutes a derivative and must be released under AGPL-3... Leading tools teams to block/quarantine as a vulnerability. Hope that helps shed some light on where they're coming from. Validity may be 100% incorrect - but that's their stance.

@bastelfreak - thanks for the message, always a pleasure! Yes sir, tail end of an SDP engagement. One of the tools team members was on a call with us moments ago and said I *could* submit a request for waiver to legal but based on past experience, even with your involvement it wouldn't be approved. I appreciate your offer to help.

**Comment by bastelfreak** [comment]
I'm SDP certified and could also talk to the customer if that helps, but I don't see another way forward. We cannot change our license just because some legal team doesn't understand it (also there's no guarantee that they understand other licenses correctly).

**Comment by prolixalias** [comment]
It would have been great if we could have talked to them - they (legal) rejected my request to even setup a meeting...

`This component is licensed under AGPL, a high-risk license currently banned from the enterprise. To avoid the virality of AGPL and minimize risk to the company's software assets, we recommend: 1) purchasing a commercial version of the software (if applicable), or 2) choosing another open source component with similar functionality, but subject to a different open source license.`

Unfortunate... We had a pretty slick use case of pdk setup for them an legal shat all over it. We tried.  :)

**Comment by bastelfreak** [comment]
Im case that comes up again we can probably sell them a commercial license.
